version: '3.4'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    networks:
      - kafka_network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_HEAP_OPTS: -Xmx256M -Xms128M
      KAFKA_ADVERTISED_HOST_NAME: iris_kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "updates:1:1, configs:1:1"
    networks:
      - kafka_network
    volumes:
      - ./kafka:/kafka
    depends_on:
      - zookeeper

  mongodb: 
    image: mongo:latest
    container_name: mongodb
    restart: always
    networks:
      - mongodb_network
    volumes:
      - ./mongodb:/data/db

  telegramconsumer:
    image: themulti0/iris_telegramconsumer:$VERSION
    build:
      context: .
      dockerfile: TelegramConsumer/Dockerfile
    container_name: telegramconsumer
    volumes:
      - './TelegramConsumer/appsettings.json:/app/appsettings.json'
    restart: always
    networks:
      - kafka_network
    depends_on:
      - kafka

  twitterproducer:
    image: themulti0/iris_twitterproducer:$VERSION
    build:
      context: .
      dockerfile: updatesproducer/Dockerfile
      args:
        PROJECT_DIR: 'twitterproducer'
    restart: always
    container_name: twitterproducer
    volumes:
      - './twitterproducer/appsettings-prod.json:/app/appsettings.json'
    networks:
      - kafka_network
      - mongodb_network
    depends_on:
      - kafka
      - mongodb

  facebookproducer:
    image: themulti0/iris_facebookproducer:$VERSION
    build:
      context: .
      dockerfile: updatesproducer/Dockerfile
      args:
        PROJECT_DIR: 'facebookproducer'
    restart: always
    container_name: facebookproducer
    volumes:
      - './facebookproducer/appsettings-prod.json:/app/appsettings.json'
    networks:
      - kafka_network
      - mongodb_network
    depends_on:
      - kafka
      - mongodb

networks:
  kafka_network:
  mongodb_network:
