version: '3.4'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
      
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "updates:1:1, tests:1:1"
    depends_on:
      - zookeeper

  mongodb: 
    image: mongo:latest
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017

  twitterproducer:
    image: ${DOCKER_REGISTRY-}twitterproducer
    build:
      context: .
      dockerfile: producer/Dockerfile
      args:
        PROJECT_DIR: 'twitterproducer'