version: '3'

services:

  twitter-scraper: 
    build: ./twitter-scraper
    image: themulti0/twitter-scraper:latest
    container_name: twitter-scraper
    restart: always
    networks:
      - iris-network

  facebook-scraper: 
    build: ./facebook-scraper
    image: themulti0/facebook-scraper:latest
    container_name: facebook-scraper
    restart: always
    networks:
      - iris-network

  iris:
    build: ./Iris
    image: themulti0/iris:latest
    container_name: iris
    restart: always
    volumes:
      - ./Iris/config:/app/config
      - ./Iris/logs:/app/logs
    networks:
      - iris-network
    depends_on:
      - twitter-scraper
      - facebook-scraper

networks:
  iris-network: