version: '3.4'

services:
  consumer:
    image: ${DOCKER_REGISTRY-}consumer
    build:
      context: .
      dockerfile: Consumer/Dockerfile

  producer:
    image: ${DOCKER_REGISTRY-}producer
    build:
      context: .
      dockerfile: Producer/Dockerfile

  twitterproducer:
    image: ${DOCKER_REGISTRY-}twitterproducer
    build:
      context: ./twitterproducer
      dockerfile: Dockerfile