version: '3.4'

services:
  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "updates:1:1, tests:1:1"
    depends_on:
      - zookeeper

  mongodb: 
    image: mongo:latest
    volumes:
      - ./mongodb:/data/db

  telegramconsumer:
    image: ${DOCKER_REGISTRY-}telegramconsumer
    build:
      context: .
      dockerfile: TelegramConsumer/Dockerfile
    depends_on: 
      - kafka