version: '3.4'

services:
  consumer:
    image: ${DOCKER_REGISTRY-}consumer
    build:
      context: .
      dockerfile: Consumer/Dockerfile

  producer:
    image: ${DOCKER_REGISTRY-}producer
    build:
      context: .
      dockerfile: Producer/Dockerfile

  twitterprovider:
    image: ${DOCKER_REGISTRY-}twitterprovider
    build:
      context: ./twitterprovider
      dockerfile: Dockerfile