name: Continuous Integration

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Iris/telegramconsumer image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: themulti0/iris_telegramconsumer
        tag_with_sha: true
        dockerfile: TelegramConsumer/Dockerfile

    - name: Build and push Iris/twitterproducer image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: themulti0/iris_twitterproducer
        tag_with_sha: true
        dockerfile: updatesproducer/Dockerfile
        build_args: PROJECT_DIR=twitterproducer

    - name: Build and push Iris/facebookproducer image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: themulti0/iris_facebookproducer
        # Automatically tags the built image with the git short SHA as per the readme
        tag_with_sha: true
        dockerfile: updatesproducer/Dockerfile
        build_args: PROJECT_DIR=facebookproducer
    
    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        VERSION: "sha-${ github.sha::7 }"
      with:
        host: ${{ secrets.VPS_HOST }}
        USERNAME: ${{ secrets.VPS_USERNAME }}
        PORT: ${{ secrets.VPS_PORT }}
        KEY: ${{ secrets.VPS_SSHKEY }}
        envs: VERSION
        script: |
          cd Iris
          git pull
          docker-compose down
          docker pull themulti0/iris_telegramconsumer:$VERSION
          docker pull themulti0/iris_twitterproducer:$VERSION
          docker pull themulti0/iris_facebookproducer:$VERSION
          docker-compose up -d
